# Generated by Django 3.2.8 on 2021-10-23 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memory', models.TextField(verbose_name='memory body')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='memory image')),
            ],
        ),
    ]
